/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.shared;

public class Library {
    public boolean someLibraryMethod() {
        System.out.println("test for branch.");
        return true;
    }
}
