/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.client;

import org.junit.jupiter.api.Test;

import java.io.IOException;

class ClientTest {
    @Test
    void initPlayerTEST() throws IOException {
        Client client = new Client(1651, "127.0.0.1");

    }
}
