/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.client;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.io.IOException;

class ClientTest {
    @Test
    void test_ClientTest() throws IOException {
        MockServer server = new MockServer(4444);
        Client client = new Client(4444,"127.0.0.1");
        server.acceptClient();
        server.getService();
        server.sendMsg(1,"HELLO CLIENT");
        Assertions.assertEquals("HELLO CLIENT",client.recvMsg());
        client.sendMsg("HELLO SERVER");
        Assertions.assertEquals("HELLO SERVER",server.recvMsg(1));
        server.getServersocket();
        server.getClientSocketList();
    }

}
