/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.client;
import edu.duke.ece651.shared.PlayerCounter;

public class Client {
    //TODO: socket client node
    //initialize one player instance
    //send/receive message to server
    public static void main(String[] args) {


    }
}
